ezplatform_page_fieldtype:
    layouts:
        sidebar:
            identifier: sidebar
            name: Right sidebar
            description: Main section with sidebar on the right
            template: layouts/sidebar.html.twig
    blocks:
        contentlist:
            views:
                contentList:
                    template: blocks/contentlist/default.html.twig
                    name: Content List